name: Build and test feature branch with Gradle

on:
  push:
    branches: feature/*

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: OnlineLibrary-Backend
    - name: Build and test with Gradle
      run: ./gradlew build
      working-directory: OnlineLibrary-Backend
