name: Main CI push

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: OnlineLibrary-Backend
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: OnlineLibrary-Backend
    - name: Check test coverage ratio
      run: ./gradlew jacocoTestCoverageVerification
      working-directory: OnlineLibrary-Backend
  deploy:
    needs: build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: 64118b4c-0551-49a2-8fa2-45cee48f24b0
        heroku_app_name: "onlinelibrary-backend-05a"
        heroku_email: "louis.t.hildebrand@gmail.com"
# TODO: Figure out how to automate integration tests as part of CI pipeline
# Possibly use https://github.com/marketplace/actions/newman-action
  integration-tests:
    needs: deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run Postman tests with Newman
      id: run-newman
      uses: anthonyvscode/newman-action@v1.1
      with:
        collection: OnlineLibrary-Backend/src/test/integration/postman-tests.json
        reporters: cli
    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
