name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - "OnlineLibrary-Frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # you can add testing for your application here with npm test
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ae3cb489-3993-49f6-88ea-73a8adc75710
          heroku_app_name: "onlinelibrary-frontend-05a"
          heroku_email: "lacroixgabriel@gmail.com"
          dontuseforce: false
